name: Build & Deploy
on:
  push:
    branches: [Dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dev branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
        
      - name: install dependence
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        script: |
          cd server
          npm i

